// Mocks generated by Mockito 5.4.6 from annotations
// in parking_demo/test/feature/util/di_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:parking_demo/parking/domain/use_cases/fetch_parking_slot.dart'
    as _i2;
import 'package:parking_demo/parking/presentation/bloc/parking_bloc.dart'
    as _i3;
import 'package:parking_demo/parking/presentation/bloc/parking_events.dart'
    as _i7;
import 'package:parking_demo/parking/presentation/bloc/parking_states.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFetchParkingSlot_0 extends _i1.SmartFake
    implements _i2.FetchParkingSlot {
  _FakeFetchParkingSlot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ParkingBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockParkingBloc extends _i1.Mock implements _i3.ParkingBloc {
  @override
  _i2.FetchParkingSlot get fetchParkingSlot =>
      (super.noSuchMethod(
            Invocation.getter(#fetchParkingSlot),
            returnValue: _FakeFetchParkingSlot_0(
              this,
              Invocation.getter(#fetchParkingSlot),
            ),
            returnValueForMissingStub: _FakeFetchParkingSlot_0(
              this,
              Invocation.getter(#fetchParkingSlot),
            ),
          )
          as _i2.FetchParkingSlot);

  @override
  _i4.ParkingState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<_i4.ParkingState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i5.dummyValue<_i4.ParkingState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.ParkingState);

  @override
  _i6.Stream<_i4.ParkingState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.ParkingState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i4.ParkingState>.empty(),
          )
          as _i6.Stream<_i4.ParkingState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> fetchParking(
    _i7.FetchedParking? event,
    _i8.Emitter<_i4.ParkingState>? emit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchParking, [event, emit]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void add(_i7.ParkingEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.ParkingEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.ParkingState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.ParkingEvent>(
    _i8.EventHandler<E, _i4.ParkingState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i7.ParkingEvent, _i4.ParkingState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i8.Change<_i4.ParkingState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
